/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as ForSchoolsRouteImport } from './routes/for-schools'
import { Route as AllServicesRouteImport } from './routes/all-services'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeaturesIndexRouteImport } from './routes/features.index'
import { Route as CatalogIndexRouteImport } from './routes/catalog.index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as FeaturesSlugRouteImport } from './routes/features.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAiStreamRouteImport } from './routes/api/ai-stream'
import { Route as AuthenticatedUpdatesRouteImport } from './routes/_authenticated/updates'
import { Route as AuthenticatedTutorRouteImport } from './routes/_authenticated/tutor'
import { Route as AuthenticatedTimerRouteImport } from './routes/_authenticated/timer'
import { Route as AuthenticatedStudyRouteImport } from './routes/_authenticated/study'
import { Route as AuthenticatedShareRouteImport } from './routes/_authenticated/share'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRankRouteImport } from './routes/_authenticated/rank'
import { Route as AuthenticatedQuestionsRouteImport } from './routes/_authenticated/questions'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedParentRouteImport } from './routes/_authenticated/parent'
import { Route as AuthenticatedOrganizationsRouteImport } from './routes/_authenticated/organizations'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedMistakesRouteImport } from './routes/_authenticated/mistakes'
import { Route as AuthenticatedMissionsRouteImport } from './routes/_authenticated/missions'
import { Route as AuthenticatedMentorRouteImport } from './routes/_authenticated/mentor'
import { Route as AuthenticatedMaterialsRouteImport } from './routes/_authenticated/materials'
import { Route as AuthenticatedMakronRouteImport } from './routes/_authenticated/makron'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedHeatmapRouteImport } from './routes/_authenticated/heatmap'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedFlashcardsRouteImport } from './routes/_authenticated/flashcards'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedExportRouteImport } from './routes/_authenticated/export'
import { Route as AuthenticatedExamsRouteImport } from './routes/_authenticated/exams'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClasschatRouteImport } from './routes/_authenticated/classchat'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedOrganizationsIndexRouteImport } from './routes/_authenticated/organizations.index'
import { Route as AuthenticatedMaterialsIndexRouteImport } from './routes/_authenticated/materials.index'
import { Route as AuthenticatedMakronIndexRouteImport } from './routes/_authenticated/makron.index'
import { Route as AuthenticatedExamsIndexRouteImport } from './routes/_authenticated/exams.index'
import { Route as AuthenticatedClassroomIndexRouteImport } from './routes/_authenticated/classroom.index'
import { Route as AuthenticatedOrganizationsOrgIdRouteImport } from './routes/_authenticated/organizations.$orgId'
import { Route as AuthenticatedMaterialsIdRouteImport } from './routes/_authenticated/materials.$id'
import { Route as AuthenticatedMakronUnitsRouteImport } from './routes/_authenticated/makron.units'
import { Route as AuthenticatedMakronLabelsRouteImport } from './routes/_authenticated/makron.labels'
import { Route as AuthenticatedMakronHistoryRouteImport } from './routes/_authenticated/makron.history'
import { Route as AuthenticatedMakronAdminRouteImport } from './routes/_authenticated/makron.admin'
import { Route as AuthenticatedExamsExamIdRouteImport } from './routes/_authenticated/exams.$examId'
import { Route as AuthenticatedClassroomClassIdRouteImport } from './routes/_authenticated/classroom.$classId'
import { Route as AuthenticatedOrganizationsOrgIdIndexRouteImport } from './routes/_authenticated/organizations.$orgId.index'
import { Route as AuthenticatedOrganizationsOrgIdProfileRouteImport } from './routes/_authenticated/organizations.$orgId.profile'
import { Route as AuthenticatedMakronUnitUnitIdRouteImport } from './routes/_authenticated/makron.unit.$unitId'
import { Route as AuthenticatedMakronSessionSessionIdRouteImport } from './routes/_authenticated/makron.session.$sessionId'
import { Route as AuthenticatedMakronResultSessionIdRouteImport } from './routes/_authenticated/makron.result.$sessionId'
import { Route as AuthenticatedMakronPackPackIdRouteImport } from './routes/_authenticated/makron.pack.$packId'
import { Route as AuthenticatedExamsSeriesSeriesIdRouteImport } from './routes/_authenticated/exams.series.$seriesId'
import { Route as AuthenticatedMakronPackPackIdIndexRouteImport } from './routes/_authenticated/makron.pack.$packId.index'
import { Route as AuthenticatedOrganizationsOrgIdManageSectionRouteImport } from './routes/_authenticated/organizations.$orgId.manage.$section'
import { Route as AuthenticatedOrganizationsOrgIdGroupGroupIdRouteImport } from './routes/_authenticated/organizations.$orgId.group.$groupId'
import { Route as AuthenticatedOrganizationsOrgIdAppAppKeyRouteImport } from './routes/_authenticated/organizations.$orgId.app.$appKey'
import { Route as AuthenticatedMakronPackPackIdDashboardRouteImport } from './routes/_authenticated/makron.pack.$packId.dashboard'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const ForSchoolsRoute = ForSchoolsRouteImport.update({
  id: '/for-schools',
  path: '/for-schools',
  getParentRoute: () => rootRouteImport,
} as any)
const AllServicesRoute = AllServicesRouteImport.update({
  id: '/all-services',
  path: '/all-services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesSlugRoute = FeaturesSlugRouteImport.update({
  id: '/features/$slug',
  path: '/features/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiStreamRoute = ApiAiStreamRouteImport.update({
  id: '/api/ai-stream',
  path: '/api/ai-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUpdatesRoute = AuthenticatedUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTutorRoute = AuthenticatedTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTimerRoute = AuthenticatedTimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudyRoute = AuthenticatedStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShareRoute = AuthenticatedShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRankRoute = AuthenticatedRankRouteImport.update({
  id: '/rank',
  path: '/rank',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuestionsRoute = AuthenticatedQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParentRoute = AuthenticatedParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrganizationsRoute =
  AuthenticatedOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMistakesRoute = AuthenticatedMistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMissionsRoute = AuthenticatedMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMentorRoute = AuthenticatedMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMaterialsRoute = AuthenticatedMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMakronRoute = AuthenticatedMakronRouteImport.update({
  id: '/makron',
  path: '/makron',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHeatmapRoute = AuthenticatedHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFlashcardsRoute = AuthenticatedFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExportRoute = AuthenticatedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamsRoute = AuthenticatedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClasschatRoute = AuthenticatedClasschatRouteImport.update({
  id: '/classchat',
  path: '/classchat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrganizationsIndexRoute =
  AuthenticatedOrganizationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrganizationsRoute,
  } as any)
const AuthenticatedMaterialsIndexRoute =
  AuthenticatedMaterialsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMaterialsRoute,
  } as any)
const AuthenticatedMakronIndexRoute =
  AuthenticatedMakronIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMakronRoute,
  } as any)
const AuthenticatedExamsIndexRoute = AuthenticatedExamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedExamsRoute,
} as any)
const AuthenticatedClassroomIndexRoute =
  AuthenticatedClassroomIndexRouteImport.update({
    id: '/classroom/',
    path: '/classroom/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdRoute =
  AuthenticatedOrganizationsOrgIdRouteImport.update({
    id: '/$orgId',
    path: '/$orgId',
    getParentRoute: () => AuthenticatedOrganizationsRoute,
  } as any)
const AuthenticatedMaterialsIdRoute =
  AuthenticatedMaterialsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedMaterialsRoute,
  } as any)
const AuthenticatedMakronUnitsRoute =
  AuthenticatedMakronUnitsRouteImport.update({
    id: '/units',
    path: '/units',
    getParentRoute: () => AuthenticatedMakronRoute,
  } as any)
const AuthenticatedMakronLabelsRoute =
  AuthenticatedMakronLabelsRouteImport.update({
    id: '/labels',
    path: '/labels',
    getParentRoute: () => AuthenticatedMakronRoute,
  } as any)
const AuthenticatedMakronHistoryRoute =
  AuthenticatedMakronHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedMakronRoute,
  } as any)
const AuthenticatedMakronAdminRoute =
  AuthenticatedMakronAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedMakronRoute,
  } as any)
const AuthenticatedExamsExamIdRoute =
  AuthenticatedExamsExamIdRouteImport.update({
    id: '/$examId',
    path: '/$examId',
    getParentRoute: () => AuthenticatedExamsRoute,
  } as any)
const AuthenticatedClassroomClassIdRoute =
  AuthenticatedClassroomClassIdRouteImport.update({
    id: '/classroom/$classId',
    path: '/classroom/$classId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdIndexRoute =
  AuthenticatedOrganizationsOrgIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdProfileRoute =
  AuthenticatedOrganizationsOrgIdProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedMakronUnitUnitIdRoute =
  AuthenticatedMakronUnitUnitIdRouteImport.update({
    id: '/unit/$unitId',
    path: '/unit/$unitId',
    getParentRoute: () => AuthenticatedMakronRoute,
  } as any)
const AuthenticatedMakronSessionSessionIdRoute =
  AuthenticatedMakronSessionSessionIdRouteImport.update({
    id: '/session/$sessionId',
    path: '/session/$sessionId',
    getParentRoute: () => AuthenticatedMakronRoute,
  } as any)
const AuthenticatedMakronResultSessionIdRoute =
  AuthenticatedMakronResultSessionIdRouteImport.update({
    id: '/result/$sessionId',
    path: '/result/$sessionId',
    getParentRoute: () => AuthenticatedMakronRoute,
  } as any)
const AuthenticatedMakronPackPackIdRoute =
  AuthenticatedMakronPackPackIdRouteImport.update({
    id: '/pack/$packId',
    path: '/pack/$packId',
    getParentRoute: () => AuthenticatedMakronRoute,
  } as any)
const AuthenticatedExamsSeriesSeriesIdRoute =
  AuthenticatedExamsSeriesSeriesIdRouteImport.update({
    id: '/series/$seriesId',
    path: '/series/$seriesId',
    getParentRoute: () => AuthenticatedExamsRoute,
  } as any)
const AuthenticatedMakronPackPackIdIndexRoute =
  AuthenticatedMakronPackPackIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMakronPackPackIdRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdManageSectionRoute =
  AuthenticatedOrganizationsOrgIdManageSectionRouteImport.update({
    id: '/manage/$section',
    path: '/manage/$section',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdGroupGroupIdRoute =
  AuthenticatedOrganizationsOrgIdGroupGroupIdRouteImport.update({
    id: '/group/$groupId',
    path: '/group/$groupId',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdAppAppKeyRoute =
  AuthenticatedOrganizationsOrgIdAppAppKeyRouteImport.update({
    id: '/app/$appKey',
    path: '/app/$appKey',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedMakronPackPackIdDashboardRoute =
  AuthenticatedMakronPackPackIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedMakronPackPackIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/all-services': typeof AllServicesRoute
  '/for-schools': typeof ForSchoolsRoute
  '/forgot': typeof ForgotRoute
  '/guide': typeof GuideRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/chat': typeof AuthenticatedChatRoute
  '/classchat': typeof AuthenticatedClasschatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exams': typeof AuthenticatedExamsRouteWithChildren
  '/export': typeof AuthenticatedExportRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/heatmap': typeof AuthenticatedHeatmapRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/makron': typeof AuthenticatedMakronRouteWithChildren
  '/materials': typeof AuthenticatedMaterialsRouteWithChildren
  '/mentor': typeof AuthenticatedMentorRoute
  '/missions': typeof AuthenticatedMissionsRoute
  '/mistakes': typeof AuthenticatedMistakesRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/organizations': typeof AuthenticatedOrganizationsRouteWithChildren
  '/parent': typeof AuthenticatedParentRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/questions': typeof AuthenticatedQuestionsRoute
  '/rank': typeof AuthenticatedRankRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/share': typeof AuthenticatedShareRoute
  '/study': typeof AuthenticatedStudyRoute
  '/timer': typeof AuthenticatedTimerRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/updates': typeof AuthenticatedUpdatesRoute
  '/api/ai-stream': typeof ApiAiStreamRoute
  '/api/chat': typeof ApiChatRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/r/$code': typeof RCodeRoute
  '/share/$token': typeof ShareTokenRoute
  '/catalog/': typeof CatalogIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/classroom/$classId': typeof AuthenticatedClassroomClassIdRoute
  '/exams/$examId': typeof AuthenticatedExamsExamIdRoute
  '/makron/admin': typeof AuthenticatedMakronAdminRoute
  '/makron/history': typeof AuthenticatedMakronHistoryRoute
  '/makron/labels': typeof AuthenticatedMakronLabelsRoute
  '/makron/units': typeof AuthenticatedMakronUnitsRoute
  '/materials/$id': typeof AuthenticatedMaterialsIdRoute
  '/organizations/$orgId': typeof AuthenticatedOrganizationsOrgIdRouteWithChildren
  '/classroom/': typeof AuthenticatedClassroomIndexRoute
  '/exams/': typeof AuthenticatedExamsIndexRoute
  '/makron/': typeof AuthenticatedMakronIndexRoute
  '/materials/': typeof AuthenticatedMaterialsIndexRoute
  '/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/exams/series/$seriesId': typeof AuthenticatedExamsSeriesSeriesIdRoute
  '/makron/pack/$packId': typeof AuthenticatedMakronPackPackIdRouteWithChildren
  '/makron/result/$sessionId': typeof AuthenticatedMakronResultSessionIdRoute
  '/makron/session/$sessionId': typeof AuthenticatedMakronSessionSessionIdRoute
  '/makron/unit/$unitId': typeof AuthenticatedMakronUnitUnitIdRoute
  '/organizations/$orgId/profile': typeof AuthenticatedOrganizationsOrgIdProfileRoute
  '/organizations/$orgId/': typeof AuthenticatedOrganizationsOrgIdIndexRoute
  '/makron/pack/$packId/dashboard': typeof AuthenticatedMakronPackPackIdDashboardRoute
  '/organizations/$orgId/app/$appKey': typeof AuthenticatedOrganizationsOrgIdAppAppKeyRoute
  '/organizations/$orgId/group/$groupId': typeof AuthenticatedOrganizationsOrgIdGroupGroupIdRoute
  '/organizations/$orgId/manage/$section': typeof AuthenticatedOrganizationsOrgIdManageSectionRoute
  '/makron/pack/$packId/': typeof AuthenticatedMakronPackPackIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/all-services': typeof AllServicesRoute
  '/for-schools': typeof ForSchoolsRoute
  '/forgot': typeof ForgotRoute
  '/guide': typeof GuideRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/chat': typeof AuthenticatedChatRoute
  '/classchat': typeof AuthenticatedClasschatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/export': typeof AuthenticatedExportRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/heatmap': typeof AuthenticatedHeatmapRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/mentor': typeof AuthenticatedMentorRoute
  '/missions': typeof AuthenticatedMissionsRoute
  '/mistakes': typeof AuthenticatedMistakesRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/parent': typeof AuthenticatedParentRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/questions': typeof AuthenticatedQuestionsRoute
  '/rank': typeof AuthenticatedRankRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/share': typeof AuthenticatedShareRoute
  '/study': typeof AuthenticatedStudyRoute
  '/timer': typeof AuthenticatedTimerRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/updates': typeof AuthenticatedUpdatesRoute
  '/api/ai-stream': typeof ApiAiStreamRoute
  '/api/chat': typeof ApiChatRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/r/$code': typeof RCodeRoute
  '/share/$token': typeof ShareTokenRoute
  '/catalog': typeof CatalogIndexRoute
  '/features': typeof FeaturesIndexRoute
  '/classroom/$classId': typeof AuthenticatedClassroomClassIdRoute
  '/exams/$examId': typeof AuthenticatedExamsExamIdRoute
  '/makron/admin': typeof AuthenticatedMakronAdminRoute
  '/makron/history': typeof AuthenticatedMakronHistoryRoute
  '/makron/labels': typeof AuthenticatedMakronLabelsRoute
  '/makron/units': typeof AuthenticatedMakronUnitsRoute
  '/materials/$id': typeof AuthenticatedMaterialsIdRoute
  '/classroom': typeof AuthenticatedClassroomIndexRoute
  '/exams': typeof AuthenticatedExamsIndexRoute
  '/makron': typeof AuthenticatedMakronIndexRoute
  '/materials': typeof AuthenticatedMaterialsIndexRoute
  '/organizations': typeof AuthenticatedOrganizationsIndexRoute
  '/exams/series/$seriesId': typeof AuthenticatedExamsSeriesSeriesIdRoute
  '/makron/result/$sessionId': typeof AuthenticatedMakronResultSessionIdRoute
  '/makron/session/$sessionId': typeof AuthenticatedMakronSessionSessionIdRoute
  '/makron/unit/$unitId': typeof AuthenticatedMakronUnitUnitIdRoute
  '/organizations/$orgId/profile': typeof AuthenticatedOrganizationsOrgIdProfileRoute
  '/organizations/$orgId': typeof AuthenticatedOrganizationsOrgIdIndexRoute
  '/makron/pack/$packId/dashboard': typeof AuthenticatedMakronPackPackIdDashboardRoute
  '/organizations/$orgId/app/$appKey': typeof AuthenticatedOrganizationsOrgIdAppAppKeyRoute
  '/organizations/$orgId/group/$groupId': typeof AuthenticatedOrganizationsOrgIdGroupGroupIdRoute
  '/organizations/$orgId/manage/$section': typeof AuthenticatedOrganizationsOrgIdManageSectionRoute
  '/makron/pack/$packId': typeof AuthenticatedMakronPackPackIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/all-services': typeof AllServicesRoute
  '/for-schools': typeof ForSchoolsRoute
  '/forgot': typeof ForgotRoute
  '/guide': typeof GuideRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/classchat': typeof AuthenticatedClasschatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exams': typeof AuthenticatedExamsRouteWithChildren
  '/_authenticated/export': typeof AuthenticatedExportRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/flashcards': typeof AuthenticatedFlashcardsRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/heatmap': typeof AuthenticatedHeatmapRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/makron': typeof AuthenticatedMakronRouteWithChildren
  '/_authenticated/materials': typeof AuthenticatedMaterialsRouteWithChildren
  '/_authenticated/mentor': typeof AuthenticatedMentorRoute
  '/_authenticated/missions': typeof AuthenticatedMissionsRoute
  '/_authenticated/mistakes': typeof AuthenticatedMistakesRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/organizations': typeof AuthenticatedOrganizationsRouteWithChildren
  '/_authenticated/parent': typeof AuthenticatedParentRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRoute
  '/_authenticated/questions': typeof AuthenticatedQuestionsRoute
  '/_authenticated/rank': typeof AuthenticatedRankRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/share': typeof AuthenticatedShareRoute
  '/_authenticated/study': typeof AuthenticatedStudyRoute
  '/_authenticated/timer': typeof AuthenticatedTimerRoute
  '/_authenticated/tutor': typeof AuthenticatedTutorRoute
  '/_authenticated/updates': typeof AuthenticatedUpdatesRoute
  '/api/ai-stream': typeof ApiAiStreamRoute
  '/api/chat': typeof ApiChatRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/r/$code': typeof RCodeRoute
  '/share/$token': typeof ShareTokenRoute
  '/catalog/': typeof CatalogIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/_authenticated/classroom/$classId': typeof AuthenticatedClassroomClassIdRoute
  '/_authenticated/exams/$examId': typeof AuthenticatedExamsExamIdRoute
  '/_authenticated/makron/admin': typeof AuthenticatedMakronAdminRoute
  '/_authenticated/makron/history': typeof AuthenticatedMakronHistoryRoute
  '/_authenticated/makron/labels': typeof AuthenticatedMakronLabelsRoute
  '/_authenticated/makron/units': typeof AuthenticatedMakronUnitsRoute
  '/_authenticated/materials/$id': typeof AuthenticatedMaterialsIdRoute
  '/_authenticated/organizations/$orgId': typeof AuthenticatedOrganizationsOrgIdRouteWithChildren
  '/_authenticated/classroom/': typeof AuthenticatedClassroomIndexRoute
  '/_authenticated/exams/': typeof AuthenticatedExamsIndexRoute
  '/_authenticated/makron/': typeof AuthenticatedMakronIndexRoute
  '/_authenticated/materials/': typeof AuthenticatedMaterialsIndexRoute
  '/_authenticated/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/_authenticated/exams/series/$seriesId': typeof AuthenticatedExamsSeriesSeriesIdRoute
  '/_authenticated/makron/pack/$packId': typeof AuthenticatedMakronPackPackIdRouteWithChildren
  '/_authenticated/makron/result/$sessionId': typeof AuthenticatedMakronResultSessionIdRoute
  '/_authenticated/makron/session/$sessionId': typeof AuthenticatedMakronSessionSessionIdRoute
  '/_authenticated/makron/unit/$unitId': typeof AuthenticatedMakronUnitUnitIdRoute
  '/_authenticated/organizations/$orgId/profile': typeof AuthenticatedOrganizationsOrgIdProfileRoute
  '/_authenticated/organizations/$orgId/': typeof AuthenticatedOrganizationsOrgIdIndexRoute
  '/_authenticated/makron/pack/$packId/dashboard': typeof AuthenticatedMakronPackPackIdDashboardRoute
  '/_authenticated/organizations/$orgId/app/$appKey': typeof AuthenticatedOrganizationsOrgIdAppAppKeyRoute
  '/_authenticated/organizations/$orgId/group/$groupId': typeof AuthenticatedOrganizationsOrgIdGroupGroupIdRoute
  '/_authenticated/organizations/$orgId/manage/$section': typeof AuthenticatedOrganizationsOrgIdManageSectionRoute
  '/_authenticated/makron/pack/$packId/': typeof AuthenticatedMakronPackPackIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/all-services'
    | '/for-schools'
    | '/forgot'
    | '/guide'
    | '/help'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/announcements'
    | '/calendar'
    | '/chat'
    | '/classchat'
    | '/dashboard'
    | '/exams'
    | '/export'
    | '/feed'
    | '/flashcards'
    | '/friends'
    | '/goals'
    | '/heatmap'
    | '/inventory'
    | '/leaderboard'
    | '/makron'
    | '/materials'
    | '/mentor'
    | '/missions'
    | '/mistakes'
    | '/notes'
    | '/notifications'
    | '/organizations'
    | '/parent'
    | '/practice'
    | '/questions'
    | '/rank'
    | '/settings'
    | '/share'
    | '/study'
    | '/timer'
    | '/tutor'
    | '/updates'
    | '/api/ai-stream'
    | '/api/chat'
    | '/features/$slug'
    | '/r/$code'
    | '/share/$token'
    | '/catalog/'
    | '/features/'
    | '/classroom/$classId'
    | '/exams/$examId'
    | '/makron/admin'
    | '/makron/history'
    | '/makron/labels'
    | '/makron/units'
    | '/materials/$id'
    | '/organizations/$orgId'
    | '/classroom/'
    | '/exams/'
    | '/makron/'
    | '/materials/'
    | '/organizations/'
    | '/exams/series/$seriesId'
    | '/makron/pack/$packId'
    | '/makron/result/$sessionId'
    | '/makron/session/$sessionId'
    | '/makron/unit/$unitId'
    | '/organizations/$orgId/profile'
    | '/organizations/$orgId/'
    | '/makron/pack/$packId/dashboard'
    | '/organizations/$orgId/app/$appKey'
    | '/organizations/$orgId/group/$groupId'
    | '/organizations/$orgId/manage/$section'
    | '/makron/pack/$packId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/all-services'
    | '/for-schools'
    | '/forgot'
    | '/guide'
    | '/help'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/announcements'
    | '/calendar'
    | '/chat'
    | '/classchat'
    | '/dashboard'
    | '/export'
    | '/feed'
    | '/flashcards'
    | '/friends'
    | '/goals'
    | '/heatmap'
    | '/inventory'
    | '/leaderboard'
    | '/mentor'
    | '/missions'
    | '/mistakes'
    | '/notes'
    | '/notifications'
    | '/parent'
    | '/practice'
    | '/questions'
    | '/rank'
    | '/settings'
    | '/share'
    | '/study'
    | '/timer'
    | '/tutor'
    | '/updates'
    | '/api/ai-stream'
    | '/api/chat'
    | '/features/$slug'
    | '/r/$code'
    | '/share/$token'
    | '/catalog'
    | '/features'
    | '/classroom/$classId'
    | '/exams/$examId'
    | '/makron/admin'
    | '/makron/history'
    | '/makron/labels'
    | '/makron/units'
    | '/materials/$id'
    | '/classroom'
    | '/exams'
    | '/makron'
    | '/materials'
    | '/organizations'
    | '/exams/series/$seriesId'
    | '/makron/result/$sessionId'
    | '/makron/session/$sessionId'
    | '/makron/unit/$unitId'
    | '/organizations/$orgId/profile'
    | '/organizations/$orgId'
    | '/makron/pack/$packId/dashboard'
    | '/organizations/$orgId/app/$appKey'
    | '/organizations/$orgId/group/$groupId'
    | '/organizations/$orgId/manage/$section'
    | '/makron/pack/$packId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-login'
    | '/all-services'
    | '/for-schools'
    | '/forgot'
    | '/guide'
    | '/help'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/announcements'
    | '/_authenticated/calendar'
    | '/_authenticated/chat'
    | '/_authenticated/classchat'
    | '/_authenticated/dashboard'
    | '/_authenticated/exams'
    | '/_authenticated/export'
    | '/_authenticated/feed'
    | '/_authenticated/flashcards'
    | '/_authenticated/friends'
    | '/_authenticated/goals'
    | '/_authenticated/heatmap'
    | '/_authenticated/inventory'
    | '/_authenticated/leaderboard'
    | '/_authenticated/makron'
    | '/_authenticated/materials'
    | '/_authenticated/mentor'
    | '/_authenticated/missions'
    | '/_authenticated/mistakes'
    | '/_authenticated/notes'
    | '/_authenticated/notifications'
    | '/_authenticated/organizations'
    | '/_authenticated/parent'
    | '/_authenticated/practice'
    | '/_authenticated/questions'
    | '/_authenticated/rank'
    | '/_authenticated/settings'
    | '/_authenticated/share'
    | '/_authenticated/study'
    | '/_authenticated/timer'
    | '/_authenticated/tutor'
    | '/_authenticated/updates'
    | '/api/ai-stream'
    | '/api/chat'
    | '/features/$slug'
    | '/r/$code'
    | '/share/$token'
    | '/catalog/'
    | '/features/'
    | '/_authenticated/classroom/$classId'
    | '/_authenticated/exams/$examId'
    | '/_authenticated/makron/admin'
    | '/_authenticated/makron/history'
    | '/_authenticated/makron/labels'
    | '/_authenticated/makron/units'
    | '/_authenticated/materials/$id'
    | '/_authenticated/organizations/$orgId'
    | '/_authenticated/classroom/'
    | '/_authenticated/exams/'
    | '/_authenticated/makron/'
    | '/_authenticated/materials/'
    | '/_authenticated/organizations/'
    | '/_authenticated/exams/series/$seriesId'
    | '/_authenticated/makron/pack/$packId'
    | '/_authenticated/makron/result/$sessionId'
    | '/_authenticated/makron/session/$sessionId'
    | '/_authenticated/makron/unit/$unitId'
    | '/_authenticated/organizations/$orgId/profile'
    | '/_authenticated/organizations/$orgId/'
    | '/_authenticated/makron/pack/$packId/dashboard'
    | '/_authenticated/organizations/$orgId/app/$appKey'
    | '/_authenticated/organizations/$orgId/group/$groupId'
    | '/_authenticated/organizations/$orgId/manage/$section'
    | '/_authenticated/makron/pack/$packId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AllServicesRoute: typeof AllServicesRoute
  ForSchoolsRoute: typeof ForSchoolsRoute
  ForgotRoute: typeof ForgotRoute
  GuideRoute: typeof GuideRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiAiStreamRoute: typeof ApiAiStreamRoute
  ApiChatRoute: typeof ApiChatRoute
  FeaturesSlugRoute: typeof FeaturesSlugRoute
  RCodeRoute: typeof RCodeRoute
  ShareTokenRoute: typeof ShareTokenRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-schools': {
      id: '/for-schools'
      path: '/for-schools'
      fullPath: '/for-schools'
      preLoaderRoute: typeof ForSchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-services': {
      id: '/all-services'
      path: '/all-services'
      fullPath: '/all-services'
      preLoaderRoute: typeof AllServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/$slug': {
      id: '/features/$slug'
      path: '/features/$slug'
      fullPath: '/features/$slug'
      preLoaderRoute: typeof FeaturesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-stream': {
      id: '/api/ai-stream'
      path: '/api/ai-stream'
      fullPath: '/api/ai-stream'
      preLoaderRoute: typeof ApiAiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/updates': {
      id: '/_authenticated/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof AuthenticatedUpdatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tutor': {
      id: '/_authenticated/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AuthenticatedTutorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/timer': {
      id: '/_authenticated/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof AuthenticatedTimerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/study': {
      id: '/_authenticated/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof AuthenticatedStudyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/share': {
      id: '/_authenticated/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof AuthenticatedShareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rank': {
      id: '/_authenticated/rank'
      path: '/rank'
      fullPath: '/rank'
      preLoaderRoute: typeof AuthenticatedRankRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/questions': {
      id: '/_authenticated/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof AuthenticatedQuestionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parent': {
      id: '/_authenticated/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AuthenticatedParentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizations': {
      id: '/_authenticated/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthenticatedOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mistakes': {
      id: '/_authenticated/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof AuthenticatedMistakesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/missions': {
      id: '/_authenticated/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof AuthenticatedMissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mentor': {
      id: '/_authenticated/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof AuthenticatedMentorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/materials': {
      id: '/_authenticated/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AuthenticatedMaterialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/makron': {
      id: '/_authenticated/makron'
      path: '/makron'
      fullPath: '/makron'
      preLoaderRoute: typeof AuthenticatedMakronRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/heatmap': {
      id: '/_authenticated/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof AuthenticatedHeatmapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flashcards': {
      id: '/_authenticated/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof AuthenticatedFlashcardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/export': {
      id: '/_authenticated/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthenticatedExportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams': {
      id: '/_authenticated/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classchat': {
      id: '/_authenticated/classchat'
      path: '/classchat'
      fullPath: '/classchat'
      preLoaderRoute: typeof AuthenticatedClasschatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizations/': {
      id: '/_authenticated/organizations/'
      path: '/'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationsRoute
    }
    '/_authenticated/materials/': {
      id: '/_authenticated/materials/'
      path: '/'
      fullPath: '/materials/'
      preLoaderRoute: typeof AuthenticatedMaterialsIndexRouteImport
      parentRoute: typeof AuthenticatedMaterialsRoute
    }
    '/_authenticated/makron/': {
      id: '/_authenticated/makron/'
      path: '/'
      fullPath: '/makron/'
      preLoaderRoute: typeof AuthenticatedMakronIndexRouteImport
      parentRoute: typeof AuthenticatedMakronRoute
    }
    '/_authenticated/exams/': {
      id: '/_authenticated/exams/'
      path: '/'
      fullPath: '/exams/'
      preLoaderRoute: typeof AuthenticatedExamsIndexRouteImport
      parentRoute: typeof AuthenticatedExamsRoute
    }
    '/_authenticated/classroom/': {
      id: '/_authenticated/classroom/'
      path: '/classroom'
      fullPath: '/classroom/'
      preLoaderRoute: typeof AuthenticatedClassroomIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizations/$orgId': {
      id: '/_authenticated/organizations/$orgId'
      path: '/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdRouteImport
      parentRoute: typeof AuthenticatedOrganizationsRoute
    }
    '/_authenticated/materials/$id': {
      id: '/_authenticated/materials/$id'
      path: '/$id'
      fullPath: '/materials/$id'
      preLoaderRoute: typeof AuthenticatedMaterialsIdRouteImport
      parentRoute: typeof AuthenticatedMaterialsRoute
    }
    '/_authenticated/makron/units': {
      id: '/_authenticated/makron/units'
      path: '/units'
      fullPath: '/makron/units'
      preLoaderRoute: typeof AuthenticatedMakronUnitsRouteImport
      parentRoute: typeof AuthenticatedMakronRoute
    }
    '/_authenticated/makron/labels': {
      id: '/_authenticated/makron/labels'
      path: '/labels'
      fullPath: '/makron/labels'
      preLoaderRoute: typeof AuthenticatedMakronLabelsRouteImport
      parentRoute: typeof AuthenticatedMakronRoute
    }
    '/_authenticated/makron/history': {
      id: '/_authenticated/makron/history'
      path: '/history'
      fullPath: '/makron/history'
      preLoaderRoute: typeof AuthenticatedMakronHistoryRouteImport
      parentRoute: typeof AuthenticatedMakronRoute
    }
    '/_authenticated/makron/admin': {
      id: '/_authenticated/makron/admin'
      path: '/admin'
      fullPath: '/makron/admin'
      preLoaderRoute: typeof AuthenticatedMakronAdminRouteImport
      parentRoute: typeof AuthenticatedMakronRoute
    }
    '/_authenticated/exams/$examId': {
      id: '/_authenticated/exams/$examId'
      path: '/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof AuthenticatedExamsExamIdRouteImport
      parentRoute: typeof AuthenticatedExamsRoute
    }
    '/_authenticated/classroom/$classId': {
      id: '/_authenticated/classroom/$classId'
      path: '/classroom/$classId'
      fullPath: '/classroom/$classId'
      preLoaderRoute: typeof AuthenticatedClassroomClassIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizations/$orgId/': {
      id: '/_authenticated/organizations/$orgId/'
      path: '/'
      fullPath: '/organizations/$orgId/'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRoute
    }
    '/_authenticated/organizations/$orgId/profile': {
      id: '/_authenticated/organizations/$orgId/profile'
      path: '/profile'
      fullPath: '/organizations/$orgId/profile'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdProfileRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRoute
    }
    '/_authenticated/makron/unit/$unitId': {
      id: '/_authenticated/makron/unit/$unitId'
      path: '/unit/$unitId'
      fullPath: '/makron/unit/$unitId'
      preLoaderRoute: typeof AuthenticatedMakronUnitUnitIdRouteImport
      parentRoute: typeof AuthenticatedMakronRoute
    }
    '/_authenticated/makron/session/$sessionId': {
      id: '/_authenticated/makron/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/makron/session/$sessionId'
      preLoaderRoute: typeof AuthenticatedMakronSessionSessionIdRouteImport
      parentRoute: typeof AuthenticatedMakronRoute
    }
    '/_authenticated/makron/result/$sessionId': {
      id: '/_authenticated/makron/result/$sessionId'
      path: '/result/$sessionId'
      fullPath: '/makron/result/$sessionId'
      preLoaderRoute: typeof AuthenticatedMakronResultSessionIdRouteImport
      parentRoute: typeof AuthenticatedMakronRoute
    }
    '/_authenticated/makron/pack/$packId': {
      id: '/_authenticated/makron/pack/$packId'
      path: '/pack/$packId'
      fullPath: '/makron/pack/$packId'
      preLoaderRoute: typeof AuthenticatedMakronPackPackIdRouteImport
      parentRoute: typeof AuthenticatedMakronRoute
    }
    '/_authenticated/exams/series/$seriesId': {
      id: '/_authenticated/exams/series/$seriesId'
      path: '/series/$seriesId'
      fullPath: '/exams/series/$seriesId'
      preLoaderRoute: typeof AuthenticatedExamsSeriesSeriesIdRouteImport
      parentRoute: typeof AuthenticatedExamsRoute
    }
    '/_authenticated/makron/pack/$packId/': {
      id: '/_authenticated/makron/pack/$packId/'
      path: '/'
      fullPath: '/makron/pack/$packId/'
      preLoaderRoute: typeof AuthenticatedMakronPackPackIdIndexRouteImport
      parentRoute: typeof AuthenticatedMakronPackPackIdRoute
    }
    '/_authenticated/organizations/$orgId/manage/$section': {
      id: '/_authenticated/organizations/$orgId/manage/$section'
      path: '/manage/$section'
      fullPath: '/organizations/$orgId/manage/$section'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdManageSectionRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRoute
    }
    '/_authenticated/organizations/$orgId/group/$groupId': {
      id: '/_authenticated/organizations/$orgId/group/$groupId'
      path: '/group/$groupId'
      fullPath: '/organizations/$orgId/group/$groupId'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdGroupGroupIdRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRoute
    }
    '/_authenticated/organizations/$orgId/app/$appKey': {
      id: '/_authenticated/organizations/$orgId/app/$appKey'
      path: '/app/$appKey'
      fullPath: '/organizations/$orgId/app/$appKey'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdAppAppKeyRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRoute
    }
    '/_authenticated/makron/pack/$packId/dashboard': {
      id: '/_authenticated/makron/pack/$packId/dashboard'
      path: '/dashboard'
      fullPath: '/makron/pack/$packId/dashboard'
      preLoaderRoute: typeof AuthenticatedMakronPackPackIdDashboardRouteImport
      parentRoute: typeof AuthenticatedMakronPackPackIdRoute
    }
  }
}

interface AuthenticatedExamsRouteChildren {
  AuthenticatedExamsExamIdRoute: typeof AuthenticatedExamsExamIdRoute
  AuthenticatedExamsIndexRoute: typeof AuthenticatedExamsIndexRoute
  AuthenticatedExamsSeriesSeriesIdRoute: typeof AuthenticatedExamsSeriesSeriesIdRoute
}

const AuthenticatedExamsRouteChildren: AuthenticatedExamsRouteChildren = {
  AuthenticatedExamsExamIdRoute: AuthenticatedExamsExamIdRoute,
  AuthenticatedExamsIndexRoute: AuthenticatedExamsIndexRoute,
  AuthenticatedExamsSeriesSeriesIdRoute: AuthenticatedExamsSeriesSeriesIdRoute,
}

const AuthenticatedExamsRouteWithChildren =
  AuthenticatedExamsRoute._addFileChildren(AuthenticatedExamsRouteChildren)

interface AuthenticatedMakronPackPackIdRouteChildren {
  AuthenticatedMakronPackPackIdDashboardRoute: typeof AuthenticatedMakronPackPackIdDashboardRoute
  AuthenticatedMakronPackPackIdIndexRoute: typeof AuthenticatedMakronPackPackIdIndexRoute
}

const AuthenticatedMakronPackPackIdRouteChildren: AuthenticatedMakronPackPackIdRouteChildren =
  {
    AuthenticatedMakronPackPackIdDashboardRoute:
      AuthenticatedMakronPackPackIdDashboardRoute,
    AuthenticatedMakronPackPackIdIndexRoute:
      AuthenticatedMakronPackPackIdIndexRoute,
  }

const AuthenticatedMakronPackPackIdRouteWithChildren =
  AuthenticatedMakronPackPackIdRoute._addFileChildren(
    AuthenticatedMakronPackPackIdRouteChildren,
  )

interface AuthenticatedMakronRouteChildren {
  AuthenticatedMakronAdminRoute: typeof AuthenticatedMakronAdminRoute
  AuthenticatedMakronHistoryRoute: typeof AuthenticatedMakronHistoryRoute
  AuthenticatedMakronLabelsRoute: typeof AuthenticatedMakronLabelsRoute
  AuthenticatedMakronUnitsRoute: typeof AuthenticatedMakronUnitsRoute
  AuthenticatedMakronIndexRoute: typeof AuthenticatedMakronIndexRoute
  AuthenticatedMakronPackPackIdRoute: typeof AuthenticatedMakronPackPackIdRouteWithChildren
  AuthenticatedMakronResultSessionIdRoute: typeof AuthenticatedMakronResultSessionIdRoute
  AuthenticatedMakronSessionSessionIdRoute: typeof AuthenticatedMakronSessionSessionIdRoute
  AuthenticatedMakronUnitUnitIdRoute: typeof AuthenticatedMakronUnitUnitIdRoute
}

const AuthenticatedMakronRouteChildren: AuthenticatedMakronRouteChildren = {
  AuthenticatedMakronAdminRoute: AuthenticatedMakronAdminRoute,
  AuthenticatedMakronHistoryRoute: AuthenticatedMakronHistoryRoute,
  AuthenticatedMakronLabelsRoute: AuthenticatedMakronLabelsRoute,
  AuthenticatedMakronUnitsRoute: AuthenticatedMakronUnitsRoute,
  AuthenticatedMakronIndexRoute: AuthenticatedMakronIndexRoute,
  AuthenticatedMakronPackPackIdRoute:
    AuthenticatedMakronPackPackIdRouteWithChildren,
  AuthenticatedMakronResultSessionIdRoute:
    AuthenticatedMakronResultSessionIdRoute,
  AuthenticatedMakronSessionSessionIdRoute:
    AuthenticatedMakronSessionSessionIdRoute,
  AuthenticatedMakronUnitUnitIdRoute: AuthenticatedMakronUnitUnitIdRoute,
}

const AuthenticatedMakronRouteWithChildren =
  AuthenticatedMakronRoute._addFileChildren(AuthenticatedMakronRouteChildren)

interface AuthenticatedMaterialsRouteChildren {
  AuthenticatedMaterialsIdRoute: typeof AuthenticatedMaterialsIdRoute
  AuthenticatedMaterialsIndexRoute: typeof AuthenticatedMaterialsIndexRoute
}

const AuthenticatedMaterialsRouteChildren: AuthenticatedMaterialsRouteChildren =
  {
    AuthenticatedMaterialsIdRoute: AuthenticatedMaterialsIdRoute,
    AuthenticatedMaterialsIndexRoute: AuthenticatedMaterialsIndexRoute,
  }

const AuthenticatedMaterialsRouteWithChildren =
  AuthenticatedMaterialsRoute._addFileChildren(
    AuthenticatedMaterialsRouteChildren,
  )

interface AuthenticatedOrganizationsOrgIdRouteChildren {
  AuthenticatedOrganizationsOrgIdProfileRoute: typeof AuthenticatedOrganizationsOrgIdProfileRoute
  AuthenticatedOrganizationsOrgIdIndexRoute: typeof AuthenticatedOrganizationsOrgIdIndexRoute
  AuthenticatedOrganizationsOrgIdAppAppKeyRoute: typeof AuthenticatedOrganizationsOrgIdAppAppKeyRoute
  AuthenticatedOrganizationsOrgIdGroupGroupIdRoute: typeof AuthenticatedOrganizationsOrgIdGroupGroupIdRoute
  AuthenticatedOrganizationsOrgIdManageSectionRoute: typeof AuthenticatedOrganizationsOrgIdManageSectionRoute
}

const AuthenticatedOrganizationsOrgIdRouteChildren: AuthenticatedOrganizationsOrgIdRouteChildren =
  {
    AuthenticatedOrganizationsOrgIdProfileRoute:
      AuthenticatedOrganizationsOrgIdProfileRoute,
    AuthenticatedOrganizationsOrgIdIndexRoute:
      AuthenticatedOrganizationsOrgIdIndexRoute,
    AuthenticatedOrganizationsOrgIdAppAppKeyRoute:
      AuthenticatedOrganizationsOrgIdAppAppKeyRoute,
    AuthenticatedOrganizationsOrgIdGroupGroupIdRoute:
      AuthenticatedOrganizationsOrgIdGroupGroupIdRoute,
    AuthenticatedOrganizationsOrgIdManageSectionRoute:
      AuthenticatedOrganizationsOrgIdManageSectionRoute,
  }

const AuthenticatedOrganizationsOrgIdRouteWithChildren =
  AuthenticatedOrganizationsOrgIdRoute._addFileChildren(
    AuthenticatedOrganizationsOrgIdRouteChildren,
  )

interface AuthenticatedOrganizationsRouteChildren {
  AuthenticatedOrganizationsOrgIdRoute: typeof AuthenticatedOrganizationsOrgIdRouteWithChildren
  AuthenticatedOrganizationsIndexRoute: typeof AuthenticatedOrganizationsIndexRoute
}

const AuthenticatedOrganizationsRouteChildren: AuthenticatedOrganizationsRouteChildren =
  {
    AuthenticatedOrganizationsOrgIdRoute:
      AuthenticatedOrganizationsOrgIdRouteWithChildren,
    AuthenticatedOrganizationsIndexRoute: AuthenticatedOrganizationsIndexRoute,
  }

const AuthenticatedOrganizationsRouteWithChildren =
  AuthenticatedOrganizationsRoute._addFileChildren(
    AuthenticatedOrganizationsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedClasschatRoute: typeof AuthenticatedClasschatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExamsRoute: typeof AuthenticatedExamsRouteWithChildren
  AuthenticatedExportRoute: typeof AuthenticatedExportRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedFlashcardsRoute: typeof AuthenticatedFlashcardsRoute
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedHeatmapRoute: typeof AuthenticatedHeatmapRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedMakronRoute: typeof AuthenticatedMakronRouteWithChildren
  AuthenticatedMaterialsRoute: typeof AuthenticatedMaterialsRouteWithChildren
  AuthenticatedMentorRoute: typeof AuthenticatedMentorRoute
  AuthenticatedMissionsRoute: typeof AuthenticatedMissionsRoute
  AuthenticatedMistakesRoute: typeof AuthenticatedMistakesRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOrganizationsRoute: typeof AuthenticatedOrganizationsRouteWithChildren
  AuthenticatedParentRoute: typeof AuthenticatedParentRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRoute
  AuthenticatedQuestionsRoute: typeof AuthenticatedQuestionsRoute
  AuthenticatedRankRoute: typeof AuthenticatedRankRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShareRoute: typeof AuthenticatedShareRoute
  AuthenticatedStudyRoute: typeof AuthenticatedStudyRoute
  AuthenticatedTimerRoute: typeof AuthenticatedTimerRoute
  AuthenticatedTutorRoute: typeof AuthenticatedTutorRoute
  AuthenticatedUpdatesRoute: typeof AuthenticatedUpdatesRoute
  AuthenticatedClassroomClassIdRoute: typeof AuthenticatedClassroomClassIdRoute
  AuthenticatedClassroomIndexRoute: typeof AuthenticatedClassroomIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedClasschatRoute: AuthenticatedClasschatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExamsRoute: AuthenticatedExamsRouteWithChildren,
  AuthenticatedExportRoute: AuthenticatedExportRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedFlashcardsRoute: AuthenticatedFlashcardsRoute,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedHeatmapRoute: AuthenticatedHeatmapRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedMakronRoute: AuthenticatedMakronRouteWithChildren,
  AuthenticatedMaterialsRoute: AuthenticatedMaterialsRouteWithChildren,
  AuthenticatedMentorRoute: AuthenticatedMentorRoute,
  AuthenticatedMissionsRoute: AuthenticatedMissionsRoute,
  AuthenticatedMistakesRoute: AuthenticatedMistakesRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOrganizationsRoute: AuthenticatedOrganizationsRouteWithChildren,
  AuthenticatedParentRoute: AuthenticatedParentRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRoute,
  AuthenticatedQuestionsRoute: AuthenticatedQuestionsRoute,
  AuthenticatedRankRoute: AuthenticatedRankRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShareRoute: AuthenticatedShareRoute,
  AuthenticatedStudyRoute: AuthenticatedStudyRoute,
  AuthenticatedTimerRoute: AuthenticatedTimerRoute,
  AuthenticatedTutorRoute: AuthenticatedTutorRoute,
  AuthenticatedUpdatesRoute: AuthenticatedUpdatesRoute,
  AuthenticatedClassroomClassIdRoute: AuthenticatedClassroomClassIdRoute,
  AuthenticatedClassroomIndexRoute: AuthenticatedClassroomIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AllServicesRoute: AllServicesRoute,
  ForSchoolsRoute: ForSchoolsRoute,
  ForgotRoute: ForgotRoute,
  GuideRoute: GuideRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiAiStreamRoute: ApiAiStreamRoute,
  ApiChatRoute: ApiChatRoute,
  FeaturesSlugRoute: FeaturesSlugRoute,
  RCodeRoute: RCodeRoute,
  ShareTokenRoute: ShareTokenRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
