DROP TABLE IF EXISTS public.account_links CASCADE;

TRUNCATE TABLE
  public.org_edu_attempts,
  public.org_edu_questions,
  public.org_edu_units,
  public.org_edu_subjects,
  public.org_edu_streaks,
  public.org_survey_responses,
  public.org_surveys,
  public.org_post_comments,
  public.org_post_likes,
  public.org_posts,
  public.org_chat_messages,
  public.org_chat_participants,
  public.org_chat_threads,
  public.org_chat_blocks,
  public.org_calendar_events,
  public.org_notifications,
  public.org_digital_ids,
  public.org_profile_fields,
  public.org_profile_years,
  public.org_profiles,
  public.org_group_members,
  public.org_groups,
  public.org_assignment_targets,
  public.org_pack_assignments,
  public.org_app_settings,
  public.organization_service_restrictions,
  public.organization_invitations,
  public.organization_join_requests,
  public.organization_members,
  public.organizations
RESTART IDENTITY CASCADE;